apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod 
spec:
  containers:
  - name: container-writing-dates 
    image: alpine 
  - name: container-serving-dates
    image: nginx:1.19.0 
    ports:
      - containerPort: 80
